version: "3.9"
services:
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=sa
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
  organizer-calendar:
    image: organizer.calendar:1.0
    build: ./organizer.calendar
    ports:
      - "15000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  organizer-web:
    image: organizer.web:1.0
    build: ./organizer.web.client
    ports:
      - "4200:4200"